# OVO BI SE TREBALO SETOVATI
# * * * * * /usr/local/bin/php /app/artisan schedule:run >> /dev/null 2>&1
services:
    php:
        build:
            context: .
            dockerfile: .server/docker/Dockerfile
            args:
                APP_UID: ${APP_UID:-1000} # Set this to your host UID: run `id -u` in terminal
                APP_GID: ${APP_GID:-1000} # Set this to your host GID: run `id -g`
        volumes:
            - ./:/app
            - ./.server/php/99-app.ini:/usr/local/etc/php/conf.d/99-app.ini
        working_dir: /app
        # TIP: Get your UID/GID with `id -u` and `id -g` on Linux/macOS
        user: "${APP_UID:-1000}:${APP_GID:-1000}" # Same here: match your host UID:GID
        depends_on:
            mysql:
                condition: service_healthy
        environment:
            LARAVEL_ENV_ENCRYPTION_KEY:
        networks:
            - kp-platform-network
        extra_hosts:
            - "host.docker.internal:host-gateway"
        healthcheck:
            test: [ "CMD", "php", "-r", "echo 'OK';" ]
            interval: 10s
            timeout: 3s
            retries: 3

    nginx:
        image: nginx:alpine
        ports:
            - "8080:80"
            - "8443:443"
        volumes:
            - ./:/app
            - ./.server/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./.server/nginx/certs:/etc/nginx/conf.d/certs
        depends_on:
            php:
                condition: service_healthy
        networks:
            - kp-platform-network
        extra_hosts:
            - "host.docker.internal:host-gateway"

    mysql:
        image: mysql:latest
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_PASSWORD: password
            MYSQL_USER: kp_platform
            MYSQL_DATABASE: kp_platform
        volumes:
            - database_data:/var/lib/mysql
            - ./.server/mysql/my.cnf:/etc/my.cnf
            - ./.server/mysql/permissions.sql:/docker-entrypoint-initdb.d/permissions.sql
        ports:
            - "127.0.0.1:3306:3306"
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            timeout: 5s
            retries: 5
            start_period: 60s
        networks:
            - kp-platform-network

    redis:
        image: redis:6.2-alpine
        container_name: app_redis
        networks:
            - kp-platform-network
        volumes:
            - redis_data:/data

networks:
    kp-platform-network:
        driver: bridge

volumes:
    database_data:
    redis_data:
